import { chromium } from '@playwright/test';
import { openDatabase } from '../src/db.js';
import { createApp } from '../src/app.js';
import { createEngine } from '../src/engine.js';
import { hashPassword } from '../src/security.js';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
const db = await openDatabase(':memory:');
const config = { appUrl: 'http://127.0.0.1:3099', sessionSecret: randomBytes(32).toString('hex'), encryptionKey: randomBytes(32).toString('hex'), passwordHash: await hashPassword('browser-test-password'), verifyToken: randomBytes(32).toString('hex'), production: false, apiVersion: 'v24.0' };
const instagram = {};
const app = await createApp({ db, config, instagram, engine: await createEngine(db, config, instagram) });
const server = app.listen(3099, '127.0.0.1');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (msg) => {if (msg.type() === 'error' && !msg.text().includes('404') && !msg.text().includes('422')) errors.push(msg.text());});
fs.mkdirSync('test-results', { recursive: true });
try {
  await page.goto(config.appUrl + '/admin');
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true });
  await page.getByLabel('Password', { exact: true }).fill('browser-test-password');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await page.waitForURL(config.appUrl + '/admin', { timeout: 5000 }).catch(async (e) => {console.log('Unexpected page:', page.url(), await page.locator('body').innerText());throw e;});
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.getByRole('link', { name: 'New automation', exact: true }).click();
  await page.getByLabel('Name', { exact: false }).fill('Free guide');
  await page.getByLabel('Reel or post link').fill('https://www.instagram.com/reel/ABC123/');
  await page.getByLabel('Keywords', { exact: true }).fill('guide, link');
  await page.getByLabel('Your message', { exact: true }).fill('Hey! Here is the guide: https://example.com/guide');
  await page.getByLabel('Public comment reply', { exact: false }).fill('Sent! Check your DMs.');
  await page.getByLabel('Follow-up message', { exact: false }).fill('You’re welcome!');
  await page.getByText('Test a comment', { exact: true }).click();
  await page.getByLabel('Example comment').fill('GUIDE please!');
  await page.getByRole('button', { name: 'Test keyword', exact: true }).click();
  await page.getByText('Match. This comment would trigger your DM when the automation is on.').waitFor();
  await page.screenshot({ path: 'test-results/form-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Save as draft', exact: true }).click();
  await page.waitForURL(config.appUrl + '/admin');
  await page.getByText('Draft saved. No messages will be sent.', { exact: true }).waitFor();
  await page.getByRole('link', { name: 'Edit', exact: true }).click();
  await page.getByRole('button', { name: 'Save & turn on', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'Connect Instagram' }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/form-mobile.png', fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)) throw new Error('Mobile form overflows');
  await page.getByRole('link', { name: 'Instagram setup', exact: true }).click();
  await page.screenshot({ path: 'test-results/settings-mobile.png', fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)) throw new Error('Mobile settings overflow');
  await page.getByRole('link', { name: 'Activity', exact: true }).click();
  await page.getByRole('heading', { name: 'No replies yet.', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await page.waitForURL(config.appUrl + '/admin/login');
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('Browser smoke passed: login, draft save, keyword preview, validation, responsive forms, settings, activity, logout.');
} finally {await browser.close();await new Promise((resolve) => server.close(resolve));db.close();}
