export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const h = escape;
const csrfInput = token => `<input type="hidden" name="_csrf" value="${h(token)}">`;
const time = value => value ? new Date(Number(value)).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }) + ' UTC' : 'Not yet';
const status = (text, tone = '') => `<span class="status ${tone}">${h(text)}</span>`;
function document(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${h(title)} · Little Chat</title><link rel="stylesheet" href="/assets/admin.css"><script src="/assets/admin.js" defer></script></head><body>${body}</body></html>`;
}
export function login(csrf, error = '') {
  return document('Log in', `<main class="login"><div class="brand">little chat<span class="brand-dot" aria-hidden="true"></span></div><h1>Welcome back.</h1><p class="muted">Log in to manage your Instagram automations.</p>${error ? `<p class="notice error" role="alert">${h(error)}</p>` : ''}<form method="post" action="/admin/login">${csrfInput(csrf)}<label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="200" autofocus><button class="primary full" type="submit">Log in</button></form><p class="small muted login-note">Private admin access.</p></main>`);
}
export function errorPage(message) {
  return document('Unable to continue', `<main class="login"><h1>Unable to continue</h1><p>${h(message)}</p><a href="/admin">Return to admin</a></main>`);
}
export function layout({ title, section, csrf, content, flash }) {
  return document(title, `<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="/admin">little chat<span class="brand-dot" aria-hidden="true"></span></a><nav aria-label="Admin"><a href="/admin" ${section === 'automations' ? 'aria-current="page"' : ''}>Automations</a><a href="/admin/activity" ${section === 'activity' ? 'aria-current="page"' : ''}>Activity</a><a href="/admin/settings" ${section === 'settings' ? 'aria-current="page"' : ''}>Instagram setup</a></nav><form method="post" action="/admin/logout">${csrfInput(csrf)}<button class="text-button" type="submit">Log out</button></form></div></header><main id="main" class="main">${flash ? `<p class="notice ${flash.error ? 'error' : 'success'}" role="${flash.error ? 'alert' : 'status'}">${h(flash.text)}</p>` : ''}${content}</main><footer>Little Chat <span aria-hidden="true">·</span> Private admin</footer>`);
}
export function dashboard(rules, connection, csrf, problems) {
  return `<div class="page-heading"><div><h1>Automations</h1><p class="muted">A comment comes in. Your reply goes out.</p></div><a href="/admin/automations/new" class="button primary">New automation</a></div>
  ${!connection?.ready ? `<div class="notice"><strong>${connection ? 'Finish connecting Instagram.' : 'Connect Instagram to start sending.'}</strong><p>You can write and save your automations now.</p><a href="/admin/settings">${connection ? 'Finish setup' : 'Connect Instagram'} <span aria-hidden="true">→</span></a></div>` : `<p class="connection-line">${status('Connected', 'good')} @${h(connection.username)} <a href="/admin/settings">Manage</a></p>`}
  ${connection?.refreshError ? `<p class="notice error" role="alert">${h(connection.refreshError)} <a href="/admin/settings">Instagram setup</a></p>` : ''}
  ${problems ? `<p class="notice error">${problems} ${problems === 1 ? 'delivery needs' : 'deliveries need'} attention. <a href="/admin/activity">View activity</a></p>` : ''}
  ${rules.length ? `<div class="rule-list">${rules.map(r => `<article class="rule"><div class="rule-main"><div class="row wrap"><h2><a href="/admin/automations/${h(r.id)}">${h(r.name)}</a></h2>${status(r.enabled ? 'On' : 'Draft / paused', r.enabled ? 'good' : '')}</div><p class="muted rule-keywords">When someone comments ${JSON.parse(r.keywords).map(k => `<code>${h(k)}</code>`).join(' or ')}</p><p class="snippet">${h(r.dm)}</p><a class="small" href="${h(r.reel_url)}" target="_blank" rel="noopener noreferrer">View reel ↗</a></div><div class="rule-actions"><a class="button" href="/admin/automations/${h(r.id)}">Edit</a>${r.enabled ? `<form method="post" action="/admin/automations/${h(r.id)}/pause">${csrfInput(csrf)}<button type="submit">Pause</button></form>` : ''}</div></article>`).join('')}</div>` : `<section class="empty"><span class="empty-symbol" aria-hidden="true">↳</span><h2>Your first automation starts here.</h2><p>Paste a reel link, choose a keyword, and write the message you want to send.</p><a class="button" href="/admin/automations/new">Create an automation</a></section>`}`;
}
export function automationForm(rule, csrf, error = '') {
  const keywords = rule.keywords ? JSON.parse(rule.keywords).join(', ') : '';
  return `<div class="narrow"><a href="/admin" class="back">← Automations</a><div class="page-heading"><div><h1>${rule.id ? 'Edit automation' : 'New automation'}</h1><p class="muted">One reel. A keyword. Your replies.</p></div></div>${error ? `<p class="notice error" role="alert">${h(error)}</p>` : ''}
  <form method="post" action="/admin/automations${rule.id ? `/${h(rule.id)}` : ''}" id="automation-form">
  ${csrfInput(csrf)}<label for="name">Name <span class="label-note">Just for you</span></label><input id="name" name="name" value="${h(rule.name)}" placeholder="September guide" required maxlength="100">
  <section class="form-section"><h2>1. When someone comments</h2><label for="reel_url">Reel or post link</label><input id="reel_url" name="reel_url" type="url" value="${h(rule.reel_url)}" placeholder="https://www.instagram.com/reel/…/" required maxlength="500" aria-describedby="reel-help"><p id="reel-help" class="help">Use a reel or post from your connected account.</p>
  <label for="keywords">Keywords</label><input id="keywords" name="keywords" value="${h(keywords)}" placeholder="guide, link" required maxlength="500" aria-describedby="keyword-help"><p id="keyword-help" class="help">Separate with commas. Matches whole words, ignoring capitals. “Guide please!” matches “guide”. If multiple rules match, the oldest one wins.</p></section>
  <section class="form-section"><h2>2. Send them a DM</h2><label for="dm">Your message</label><textarea id="dm" name="dm" rows="5" required maxlength="1000" placeholder="Hey! Here’s the guide you asked for: https://…">${h(rule.dm)}</textarea><p class="help">You can include a link. Instagram allows one initial DM per comment.</p>
  <label for="comment_reply">Public comment reply <span class="label-note">Optional</span></label><textarea id="comment_reply" name="comment_reply" rows="2" maxlength="1000" placeholder="Sent! Check your DMs.">${h(rule.comment_reply)}</textarea><p class="help">Posted after Instagram accepts your DM. Add one reply per line to randomly choose between variations.</p></section>
  <section class="form-section"><h2>3. If they reply to your DM</h2><label for="followup">Follow-up message <span class="label-note">Optional</span></label><textarea id="followup" name="followup" rows="3" maxlength="1000" placeholder="You’re welcome! Let me know how you get on.">${h(rule.followup)}</textarea><p class="help">Sent once after their first text reply, within Instagram’s 24-hour reply window. Leave blank to handle replies yourself.</p></section>
  <details class="test-area"><summary>Test a comment</summary><p class="help">Preview the keyword match. This does not send anything to Instagram.</p><label for="test_comment">Example comment</label><input id="test_comment" placeholder="Guide please!" maxlength="1000"><button type="button" id="test-keyword">Test keyword</button><p id="test-result" role="status"></p></details>
  <div class="form-actions"><button class="primary" name="intent" value="enable" type="submit">${rule.enabled ? 'Save & keep on' : 'Save & turn on'}</button><button name="intent" value="draft" type="submit">Save as draft</button><a href="/admin">Cancel</a></div><p class="help">Turning this on applies to new comments. Saving an edit cancels queued replies with the previous copy.</p></form></div>`;
}
export function activity(jobs, csrf, page, hasMore) {
  const labels = { dm: 'Direct message', comment: 'Comment reply', followup: 'Follow-up DM' };
  return `<div class="page-heading"><div><h1>Activity</h1><p class="muted">What was sent, what’s waiting, and what needs attention.</p></div><a class="button" href="/admin/activity">Refresh</a></div>${jobs.length ? `<div class="activity-list">${jobs.map(j => `<article class="activity-item"><div class="row wrap"><h2>${h(labels[j.kind])}</h2>${status(j.status === 'review' ? 'Check Instagram' : j.status === 'pending' && j.depends_on && j.dependency_status !== 'sent' ? 'Waiting for DM' : j.status, j.status === 'sent' ? 'good' : ['review', 'failed', 'expired'].includes(j.status) ? 'bad' : '')}</div><p class="small muted"><a href="/admin/automations/${h(j.automation_id)}">${h(j.automation_name)}</a> · ${h(time(j.created_at))}</p><p class="message-text">${h(j.text)}</p><p class="small muted">${j.kind === 'followup' ? 'Recipient' : 'Comment'} ID: <code>${h(j.target)}</code></p>${j.error ? `<p class="delivery-error">${h(j.error)}</p>` : ''}${['failed', 'review'].includes(j.status) ? `<div class="retry-actions"><form method="post" action="/admin/jobs/${j.id}/retry">${csrfInput(csrf)}${j.status === 'review' ? '<label class="check"><input type="checkbox" name="checked" value="yes" required> I checked Instagram. This was not already sent.</label>' : ''}<button type="submit">Retry delivery</button></form><form method="post" action="/admin/jobs/${j.id}/dismiss">${csrfInput(csrf)}<button class="text-button" type="submit">Dismiss</button></form></div>` : j.status === 'pending' ? `<form method="post" action="/admin/jobs/${j.id}/dismiss">${csrfInput(csrf)}<button class="text-button" type="submit">Cancel delivery</button></form>` : ''}</article>`).join('')}</div><div class="pagination">${page > 1 ? `<a href="/admin/activity?page=${page - 1}">← Newer</a>` : '<span></span>'}<span class="muted">Page ${page}</span>${hasMore ? `<a href="/admin/activity?page=${page + 1}">Older →</a>` : '<span></span>'}</div>` : '<section class="empty"><h2>No replies yet.</h2><p>After you turn on an automation, matching comments and delivery results will appear here.</p><a href="/admin">View automations</a></section>'}<p class="help">“Sent” means Instagram accepted the request; it does not confirm the person read it. Times are in UTC.</p>`;
}
export function settings({ csrf, connection, config, verified, lastWebhook }) {
  return `<div class="narrow"><div class="page-heading"><div><h1>Instagram setup</h1><p class="muted">Connect your account once, then manage your automations.</p></div></div>
  ${connection ? `<div class="notice"><div class="row wrap"><strong>@${h(connection.username)}</strong>${status(connection.ready ? 'Subscribed' : 'Setup incomplete', connection.ready ? 'good' : '')}</div><p class="small">Last Instagram webhook: ${h(time(lastWebhook))}</p>${connection.expiresAt ? `<p class="small">Token expires: ${h(time(connection.expiresAt))}</p>` : '<p class="small">Token expiry is unknown until its first successful refresh.</p>'}${connection.refreshError ? `<p class="delivery-error">${h(connection.refreshError)}</p>` : ''}</div>` : ''}
  <section class="setup-section"><h2>1. Get your Instagram credentials</h2><ol class="instructions"><li>Your Instagram account needs to be a <strong>Business or Creator</strong> account.</li><li>Open <a href="https://developers.facebook.com/apps/" target="_blank" rel="noopener noreferrer">Meta for Developers ↗</a>, create an app with the Instagram API, and use <strong>Instagram API with Instagram Login</strong>.</li><li>Add your own Instagram account as an app tester/account and accept its invitation in Instagram. Enable access to messages in Instagram’s connected tools settings.</li><li>Give the app these permissions: <code>instagram_business_basic</code>, <code>instagram_business_manage_comments</code>, and <code>instagram_business_manage_messages</code>.</li><li>In <strong>Instagram → API setup with Instagram business login</strong>, choose <strong>Generate token</strong> next to your account. Dashboard tokens are long-lived (60 days). Also copy your app secret from the Meta app dashboard.</li></ol><p class="help">For your own account, use the app’s permitted test/standard access where available. Meta may require review or additional setup for your app. <a href="https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/" target="_blank" rel="noopener noreferrer">Meta setup guide ↗</a></p>
  <form method="post" action="/admin/settings/connect">${csrfInput(csrf)}<label for="token">Instagram access token</label><input id="token" type="password" name="token" required maxlength="4096" autocomplete="off" spellcheck="false" placeholder="Paste your token"><label for="app_secret">Meta app secret</label><input id="app_secret" name="app_secret" type="password" required minlength="32" maxlength="32" autocomplete="off" spellcheck="false" placeholder="Paste your app secret"><p class="help">Stored encrypted on the server. Saved secrets are never shown here.</p><button class="primary" type="submit">${connection ? 'Update connection' : 'Connect account'}</button></form></section>
  <section class="setup-section"><h2>2. Set up Instagram webhooks</h2>${config.appUrl.startsWith('http:') ? '<p class="notice">This is running locally. Meta needs a public HTTPS address to deliver comments. Deploy this app, set APP_URL to that address, then use the callback below.</p>' : ''}<p>In your Meta app’s Instagram webhook settings, enter:</p><label for="callback">Callback URL</label><div class="copy-row"><input id="callback" readonly value="${h(config.appUrl)}/webhooks/instagram"><button type="button" data-copy="callback">Copy</button></div><label for="verify">Verify token</label><div class="copy-row"><input id="verify" readonly value="${h(config.verifyToken)}"><button type="button" data-copy="verify">Copy</button></div><p class="help">Choose “Verify and save” in Meta, then subscribe to the <code>comments</code> and <code>messages</code> webhook fields.</p><p>${status(verified ? 'Callback verified' : 'Waiting for Meta verification', verified ? 'good' : '')}</p>
  <form method="post" action="/admin/settings/subscribe">${csrfInput(csrf)}<button class="primary" type="submit" ${!connection || !verified ? 'disabled' : ''}>Enable Instagram webhooks</button></form><p class="help">After verifying in Meta, <a href="/admin/settings">refresh this page</a> to enable the button. Then test with a real comment from another account.</p></section>
  ${connection ? `<section class="setup-section"><h2>Connection maintenance</h2><p class="muted">Long-lived tokens are refreshed automatically each day while the server is running. A token must be at least 24 hours old to refresh.</p><div class="row wrap"><form method="post" action="/admin/settings/refresh">${csrfInput(csrf)}<button type="submit">Refresh token now</button></form><form method="post" action="/admin/settings/disconnect" data-confirm="Disconnect Instagram and pause all automations?">${csrfInput(csrf)}<button class="danger" type="submit">Disconnect account</button></form></div></section>` : ''}
  <details class="setup-section"><summary>Change admin password</summary><form method="post" action="/admin/settings/password">${csrfInput(csrf)}<label for="current_password">Current password</label><input id="current_password" name="current_password" type="password" required autocomplete="current-password" maxlength="200"><label for="new_password">New password</label><input id="new_password" name="new_password" type="password" required autocomplete="new-password" minlength="12" maxlength="200"><p class="help">At least 12 characters. Changing it signs out other sessions.</p><button type="submit">Update password</button></form></details><p id="copy-status" role="status" class="small muted"></p></div>`;
}
